version: "3.2"

services:
  node:
    build: .
    image: chainify/substrate-nolik-dev
    container_name: node-nolik
    ports:
      - "9944:9944"
    tty: true
    stdin_open: true
    command: bash -c "./target/release/node-nolik --dev --ws-external"
